### ISSUE TITLE
The function 'vl_argparsepos' corresponding to the input parameter of type 'struct' is not defined

### ISSUE THREAD

**Issue by Errorkiller** [albanie/mcnExtraLayers#4]
hi,
l have this problem ,so how can i solve it!

**Comment by albanie** [comment]
Hi @QiangZhao666, just to repeat my answer for [here](https://github.com/albanie/mcnExtraLayers/issues/3), this function is part of https://github.com/vlfeat/autonn - apologies, I will add that to the dependencies.
